# Copyright 2023 Aineko Authors
# SPDX-License-Identifier: Apache-2.0
pipeline:
  name: routing_example

  default_node_settings:
    num_cpus: 0.5

  nodes:
    CoinbaseBook:
      class: aineko.extras.WebSocket
      outputs:
        - coinbase
      node_params:
        max_retries: 2
        url: "wss://ws-feed.exchange.coinbase.com"
        init_messages:
          - {"type": "subscribe", "channels": [{"name": "ticker", "product_ids": ["BTC-USD"]}]}

    BinanceBook:
      class: aineko.extras.WebSocket
      outputs:
        - binance
      node_params:
        max_retries: 2
        url: "wss://stream.binance.us:9443/ws/btcusdt@bookTicker"

    AlpacaBook:
      class: aineko.extras.WebSocket
      outputs:
        - alpaca
      node_params:
        max_retries: 2
        url: "wss://stream.data.alpaca.markets/v1beta3/crypto/us"
        init_messages:
          - {"action": "auth", "key": "{$ALPACA_API_KEY}", "secret": "{$ALPACA_API_SECRET}"}
          - action: "subscribe"
            quotes: ["BTC/USD"]

  datasets:
    coinbase:
      type: kafka_stream
    binance:
      type: kafka_stream
    alpaca:
      type: kafka_stream
    uniswap:
      type: kafka_stream
